<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('4Web - ZF2')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>

    </head>
    <body>        
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner" style="background-image: linear-gradient(to bottom, #030b6b, #01031f)"> <!--linear-gradient(to bottom, #05bffa, #5776b9-->
                <div class="container" style="height: 50px">                    
                    <div class="nav-collapse collapse">
                        <a class="brand" href="<?php echo $this->url('livraria-home') ?>"><h3 style="margin-top: -10px; color: #fff">For Web</h3></a>
                        <?php if ($this->UserIdentity('LivrariaAdmin')): ?>
                        <span class="pull-right"><a href="<?php echo $this->url('livraria-admin-logout') ?>" class="btn">Sair</a></span>
                        <?php endif; ?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <?php if ($this->UserIdentity('LivrariaAdmin')): ?>
        <div class="navbar navbar-fixed-top" style="margin-top: 50px">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <div class="nav-collapse collapse">
                        <ul class="nav" role="navigation">
                            <li class="dropdown">
                                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">LIVRARIA</a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('livraria-home') ?>">Livraria</a></li>
                                    <li class="divider"></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('livraria-admin', array('controller' => 'categorias', 'action' => 'index')) ?>">Categorias</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('livraria-admin', array('controller' => 'livros', 'action' => 'index')) ?>">Livros</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->url('livraria-admin', array('controller' => 'users', 'action' => 'index')) ?>">Usuários</a></li>
                                </ul>
                            </li>
                            <li class="divider-vertical"></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <?php endif; ?>
        <br />
        <div class="container" style="margin-top: 20px;">
            
            <?php echo $this->content; ?>
            
        </div> <!-- /container -->        
        <?php echo $this->inlineScript() ?>        
        <div style="position:fixed; bottom:0; width:100%; background-image: linear-gradient(to bottom, #030B6B, #01031F); height: 30px">
            <a class="brand" href="http://www.globo.com" style="text-decoration: none"><footer style="color: #fff; text-align: right; 
            margin: 10px 10px 0px 0px; font-size: 11px; font-family: sans-serif;"><em>by For Web Sistemas</em></footer></a>           
        </div>
    </body>
    
</html>
